source = /home/$USER/.cache/wal/colors-hyprland
wallpaper {
    monitor = desc:Microstep MAG274QRF-QD CA8A291900004
    path =  $wallpaper
    fit_mode = cover
}

wallpaper {
 monitor = desc:ASUSTek COMPUTER INC ASUS VG246 N2LMTF000371
 path = ~/Downloads/Pictures/ghostinshell-night.jpg
 fit_mode = cover
}
splash = false
