wallpaper {
	monitor = DP-2
	path =  ~/Downloads/Pictures/toyota-supra-need-for-speed-city-4k-1q-2560x1440.jpg
	fit_mode = cover
}

wallpaper {
	monitor = HDMI-A-1
	path = ~/Downloads/Pictures/one_punch_tournament.jpeg
	fit_mode = cover
}
splash = false
