source = /home/$USER/.cache/wal/colors-hyprland

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor = desc:Microstep MAG274QRF-QD CA8A291900004
    path = $wallpaper
    blur_size = 3
    blur_passes = 2
}

background {
    monitor = desc:ASUSTek COMPUTER INC ASUS VG246 N2LMTF000371
    path =
}

input-field {
    monitor = desc:Microstep MAG274QRF-QD CA8A291900004
    size = 20%, 5%
    outline_thickness = 1
    inner_color = $backgroundCol
    outer_color = $backgroundCol $backgroundCol
    check_color= $backgroundCol $backgroundCol
    fail_color= $backgroundCol $backgroundCol
    font_color = $color9
    fade_on_empty = false
    font_family = JetBrains Mono Nerd Font
    shadow_color = rgba(0,0,0,0.5)
    shadow_passes = 2
    shadow_size = 2
    rounding = 20
    placeholder_text = <i></i>
    fail_timeout = 300
    position = 0, -100
    halign = center
    valign = center
    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.5
    dots_rounding = 10
    fade_timeout = 300
    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true
    position = 0, 1%
    halign = center
    valign = center
}

# Offset hour indicator
label {
    monitor = desc:Microstep MAG274QRF-QD CA8A291900004
    #text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    text = cmd[update:1000] date +"<b>%I</b>"
    color = $color9
    font_size = 100
    font_family = JetBrains Mono Nerd Font
    shadow_passes = 0
    shadow_size = 5
    position = -1%, 15%
    halign = center
    valign = center
}
label {
    monitor = desc:Microstep MAG274QRF-QD CA8A291900004
    text = cmd[update:1000] date +"<b>%M</b>"
    font_size = 100
    font_family = JetBrains Mono Nerd Font
    shadow_passes = 0
    shadow_size = 5
    position = 5%, 10%
    halign = center
    valign = center
}
# DATE
label {
    monitor = desc:Microstep MAG274QRF-QD CA8A291900004
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 25
    font_family = JetBrains Mono Nerd Font

    position = 0, 0
    halign = center
    valign = top
}

