# Preload wallpaper into memory
preload = ~/Downloads/toyota-supra-need-for-speed-city-4k-1q-2560x1440.jpg
preload = ~/Downloads/one_punch_tournament.jpeg

# Set Wallpaper from preload pngs
wallpaper = DP-3, ~/Downloads/toyota-supra-need-for-speed-city-4k-1q-2560x1440.jpg
wallpaper = HDMI-A-2, ~/Downloads/one_punch_tournament.jpeg
